#!/bin/bash

#SBATCH --job-name=bam_to_fastq
#SBATCH --cpus-per-task=10 #number of cores to use
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00 #amount of time for the whole job
#SBATCH --partition=standard #the queue/partition to run on
#SBATCH --account=sheynkman_lab
#SBATCH --output=%x-%j.log
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=yqy3cu@virginia.edu

cd /project/sheynkman/users/emily/emilyfwatts/LRP_multisample_compare
module load gcc/11.4.0  openmpi/4.1.4 python/3.11.4 bioconda/py3.10 git-lfs/2.10.0
module load samtools/1.17

# read 1
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-1-flnc.bam > full_haec/input_data/fastq/Sample-1-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-2-flnc.bam > full_haec/input_data/fastq/Sample-2-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-3-flnc.bam > full_haec/input_data/fastq/Sample-3-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-4-flnc.bam > full_haec/input_data/fastq/Sample-4-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-5-flnc.bam > full_haec/input_data/fastq/Sample-5-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-6-flnc.bam > full_haec/input_data/fastq/Sample-6-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio-Sample-7-flnc.bam > full_haec/input_data/fastq/Sample-7-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio_Sample8-flnc.bam > full_haec/input_data/fastq/Sample-8-flnc_read1.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Bio_Sample_9-flnc.bam > full_haec/input_data/fastq/Sample-9-flnc_read1.fastq

# read 2
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-01_-3619-flnc-1.bam > full_haec/input_data/fastq/Sample-1-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-02_-3619-flnc-2.bam > full_haec/input_data/fastq/Sample-2-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-03-3619-flnc-3.bam > full_haec/input_data/fastq/Sample-3-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-04_-3619-flnc-4.bam > full_haec/input_data/fastq/Sample-4-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-05_-3619-flnc-5.bam > full_haec/input_data/fastq/Sample-5-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-06_-3619-flnc-6.bam > full_haec/input_data/fastq/Sample-6-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-07_-3619-flnc-7.bam > full_haec/input_data/fastq/Sample-7-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-08_-3619-flnc-8.bam > full_haec/input_data/fastq/Sample-8-flnc_read2.fastq
samtools fastq /project/sheynkman/raw_data/PacBio/stc655-yohannes-kinnex/STC655_Kinnex_Data/STC655_Airway_epithelial_Kinnex-Read2-_Barcode-09_-3619-flnc-9.bam > full_haec/input_data/fastq/Sample-9-flnc_read2.fastq